name = "leanwuzla"
version = "0.1.0"
defaultTargets = ["Leanwuzla", "leanwuzla"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Leanwuzla"

[[lean_exe]]
name = "leanwuzla"
root = "Main"
supportInterpreter = true

[[require]]
scope = "leanprover"
name = "Cli"
rev = "v4.19.0-rc2"
